services:
  - type: web
    name: audiscript-be
    env: docker
    plan: free
    buildCommand: go build -o app ./cmd/api
    startCommand: ./app
    envVars:
      - key: GIN_MODE
        value: release
